fix(trace): resolve pip conflicts
I could not upgrade the packages in:
trace/cloud-trace-demo-app-opentelemetry/app/requirements.txt
because of the following error:

AttributeError: 'DefaultTracerProvider' object has no attribute
'add_span_processor'

fixes #5245