Reverting back to python38
google-python-cloud-debugger does not support Python 3.9[1] yet thus app engine resulted in error when deploying.

Error type: UNKNOWN
Error message: Collecting Flask==1.1.2
  Using cached Flask-1.1.2-py2.py3-none-any.whl (94 kB)
ERROR: Could not find a version that satisfies the requirement google-python-cloud-debugger==2.15
ERROR: No matching distribution found for google-python-cloud-debugger==2.15

Supported version:
Python :: 2.7
Python :: 3.6
Python :: 3.7
Python :: 3.8

Current Resolution:
Reverting back to python38 to match with google-python-cloud-debugger v2.15 supported python version

[1] https://pypi.org/project/Error type: UNKNOWN
Error message: Collecting Flask==1.1.2
  Using cached Flask-1.1.2-py2.py3-none-any.whl (94 kB)
ERROR: Could not find a version that satisfies the requirement google-python-cloud-debugger==2.15
ERROR: No matching distribution found for google-python-cloud-debugger==2.15/#history