Latest version of Werkzeug raises ImportError
The latest version of Werkzeug (0.13) released on December 7th raises an ImportError when Flask is imported on app engine.

```ImportError: cannot import name SpooledTemporaryFile```

App engine standard does not support SpooledTemporaryFile, so we should explicitly instruct users to install Werkzeug==0.12.2 (last working version).