Remove unnecessary order_by field in a query
The start_at_name query has an extra order_by that causes an error.

Removes the following error:

ValueError: The "order by" field path 'state' is not present in the cursor data {'name': 'Springfield'}. All fields sent to ``order_by()`` must be present in the fields if passed to one of ``start_at()`` / ``start_after()`` / ``end_before()`` / ``end_at()`` to define a cursor.