chore(bigquery): remove redundant dependency on pytest
The BQML dependency on pytest is redundant with the central testing
dependencies. Removing this dependency resolves a `TypeError: attrib()
got an unexpected keyword argument 'convert'` test failure caused by
incompatible versions.